version: "3.3"

services:
  nextjs-do-scg:
    container_name: nextjs-do-scg
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    environment:
      CORSHEADER: "http://127.0.0.1:6319"
      PROXY: "true"
      HTTPS_METHOD: noredirect # support both http and https